
export enum NotificationEnum{
  NOUVELLE_COMMANDE= 0,
  NOUVEAU_CLIENT= 1,
  NOUVEAU_PRESTATAIRE = 2,
  NOUVEAU_DEVIS = 3,
  DEVIS_VALIDE = 4,
  PRESTATION_TERMINEE_PRESTATAIRE = 5,
  PRESTATION_TERMINEE_CLIENT= 6,
  COMMANDE_VALIDE= 7  ,
  PROPOSITION_PRESTATAIRE= 8 ,
  DEVIS_A_REGLER= 9,
  DEVIS_PAYE= 10,
  DEVIS_REFUSE= 11,
  DEVIS_ANNULE= 12  
}